/**
 * Spot the fake — game logic.
 *
 * Two images per round: one real Wikipedia photograph, one generated by AI. The
 * player picks the one they believe is real, and the reveal names the specific
 * tells rather than just announcing the answer.
 *
 * No sign-in and no API calls at play time: the fakes are generated ahead of
 * time and committed, so the game works offline after the images load.
 */
(function () {
	"use strict";

	const STREAK_KEY = "spot-the-fake.streak";
	const BEST_KEY = "spot-the-fake.best";

	/** Seconds to choose. The quest asks for a timer, so running out is a miss. */
	const ROUND_SECONDS = 15;

	const $ = (id) => document.getElementById(id);

	/** Fisher-Yates, so the fake is not always in the same slot. */
	function shuffle(items, random) {
		const copy = items.slice();
		for (let i = copy.length - 1; i > 0; i -= 1) {
			const j = Math.floor(random() * (i + 1));
			[copy[i], copy[j]] = [copy[j], copy[i]];
		}
		return copy;
	}

	/**
	 * Decide which slot the real image occupies and build the card list.
	 * Split out from rendering so it can be tested without a DOM.
	 */
	function buildRound(round, random) {
		const realFirst = random() < 0.5;
		const cards = realFirst
			? [
					{ kind: "real", src: round.real },
					{ kind: "fake", src: round.fake },
			  ]
			: [
					{ kind: "fake", src: round.fake },
					{ kind: "real", src: round.real },
			  ];
		return {
			id: round.id,
			label: round.label,
			credit: round.credit,
			source: round.source,
			tells: round.tells,
			cards,
			realIndex: cards.findIndex((card) => card.kind === "real"),
		};
	}

	/** The verdict line, given the pick and the answer. */
	function verdictFor(pickedIndex, realIndex, round) {
		// pickedIndex of -1 means the timer ran out before a choice was made.
		const timedOut = pickedIndex < 0;
		const correct = !timedOut && pickedIndex === realIndex;
		return {
			correct,
			timedOut,
			title: correct ? "Correct" : timedOut ? "Out of time" : "Not this time",
			lead: correct
				? `That one is the real photograph of a ${round.label.toLowerCase()}.`
				: timedOut
					? `The timer ran out. The real photograph was image ${realIndex + 1}.`
					: "The real photograph was the other one — this is the AI fake.",
			tells: round.tells,
		};
	}

	/** A round order that does not repeat until every round has been seen. */
	function nextQueue(rounds, random) {
		return shuffle(rounds, random);
	}

	const game = {
		rounds: [],
		queue: [],
		current: null,
		streak: 0,
		best: 0,
		roundNumber: 1,
		answered: false,
		random: Math.random,
		timerId: null,
		deadline: 0,
	};

	/** Paint the bar and the countdown; called on a short interval. */
	function paintTimer() {
		const remaining = Math.max(0, game.deadline - Date.now());
		const seconds = remaining / 1000;
		const ratio = remaining / (ROUND_SECONDS * 1000);
		$("timer-bar").style.width = `${Math.max(0, Math.min(1, ratio)) * 100}%`;
		const label = $("timer-label");
		const wrap = $("timer-wrap");
		label.textContent = `${seconds.toFixed(1)}s left`;
		if (seconds <= 5) {
			label.classList.add("warn");
			wrap.classList.add("warn");
		} else {
			label.classList.remove("warn");
			wrap.classList.remove("warn");
		}
	}

	function stopTimer() {
		if (game.timerId !== null) {
			clearInterval(game.timerId);
			game.timerId = null;
		}
	}

	function startTimer() {
		stopTimer();
		game.deadline = Date.now() + ROUND_SECONDS * 1000;
		paintTimer();
		game.timerId = setInterval(() => {
			paintTimer();
			if (Date.now() >= game.deadline) {
				stopTimer();
				// Out of time: reveal the answer with no pick.
				answer(-1);
			}
		}, 100);
	}

	function readNumber(storage, key) {
		try {
			const value = Number(storage.getItem(key));
			return Number.isFinite(value) && value > 0 ? value : 0;
		} catch {
			return 0;
		}
	}

	function writeNumber(storage, key, value) {
		try {
			storage.setItem(key, String(value));
		} catch {
			/* private mode: scores simply do not persist */
		}
	}

	function paintStats() {
		$("streak").textContent = String(game.streak);
		$("best").textContent = String(game.best);
		$("round").textContent = String(game.roundNumber);
	}

	function nextRound() {
		if (game.queue.length === 0) game.queue = nextQueue(game.rounds, game.random);
		const round = game.queue.shift();
		game.current = buildRound(round, game.random);
		game.answered = false;

		$("subject").textContent = `Both show a ${game.current.label.toLowerCase()}.`;
		$("verdict").hidden = true;
		$("next").hidden = true;
		$("restart").hidden = true;
		$("score-hint").textContent = "";
		paintStats();

		const board = $("board");
		board.innerHTML = "";
		game.current.cards.forEach((card, index) => {
			const element = document.createElement("button");
			element.className = "card";
			element.type = "button";
			element.setAttribute("aria-label", `Image ${index + 1} of 2`);
			const image = document.createElement("img");
			image.src = card.src;
			image.alt = `Candidate ${index + 1}: a ${game.current.label.toLowerCase()}`;
			image.loading = "eager";
			const tag = document.createElement("span");
			tag.className = "tag";
			tag.textContent = `Image ${index + 1}`;
			element.appendChild(image);
			element.appendChild(tag);
			element.addEventListener("click", () => answer(index));
			board.appendChild(element);
		});
		startTimer();
	}

	function answer(pickedIndex) {
		if (game.answered) return;
		game.answered = true;
		stopTimer();

		const verdict = verdictFor(pickedIndex, game.current.realIndex, game.current);

		const cards = Array.from($("board").children);
		cards.forEach((card, index) => {
			card.setAttribute("aria-disabled", "true");
			card.disabled = true;
			if (index === game.current.realIndex) card.classList.add("correct");
			else if (index === pickedIndex) card.classList.add("wrong");
			else card.classList.add("dimmed");
		});

		if (verdict.correct) {
			game.streak += 1;
			if (game.streak > game.best) {
				game.best = game.streak;
				writeNumber(window.localStorage, BEST_KEY, game.best);
			}
			writeNumber(window.localStorage, STREAK_KEY, game.streak);
		} else {
			game.streak = 0;
			writeNumber(window.localStorage, STREAK_KEY, 0);
		}
		paintStats();

		const panel = $("verdict");
		panel.hidden = false;
		panel.innerHTML = "";

		const title = document.createElement("h3");
		title.className = verdict.correct ? "good" : "bad";
		title.textContent = verdict.title;
		panel.appendChild(title);

		const lead = document.createElement("p");
		lead.textContent = verdict.lead;
		lead.style.margin = "0";
		panel.appendChild(lead);

		const heading = document.createElement("div");
		heading.textContent = "What gave the fake away:";
		heading.style.marginTop = "10px";
		heading.style.fontWeight = "600";
		panel.appendChild(heading);

		const list = document.createElement("ul");
		for (const tell of verdict.tells) {
			const item = document.createElement("li");
			item.textContent = tell;
			list.appendChild(item);
		}
		panel.appendChild(list);

		const credit = document.createElement("div");
		credit.className = "credit";
		credit.append("Real photo: ");
		const link = document.createElement("a");
		link.href = game.current.source;
		link.target = "_blank";
		link.rel = "noopener";
		link.textContent = game.current.credit;
		credit.appendChild(link);
		credit.append(" (Wikipedia). Fake: flux.1-schnell via Pollinations.");
		panel.appendChild(credit);

		$("next").hidden = false;
		$("restart").hidden = false;
		$("score-hint").textContent = game.streak > 0 ? `Streak ${game.streak}` : "Streak reset";
		$("next").focus();
	}

	function restart() {
		game.streak = 0;
		game.roundNumber = 1;
		game.queue = nextQueue(game.rounds, game.random);
		writeNumber(window.localStorage, STREAK_KEY, 0);
		paintStats();
		nextRound();
	}

	async function boot() {
		const response = await fetch("rounds.json");
		if (!response.ok) throw new Error(`could not load rounds (HTTP ${response.status})`);
		game.rounds = await response.json();
		if (!Array.isArray(game.rounds) || game.rounds.length === 0) {
			throw new Error("no rounds available");
		}
		game.best = readNumber(window.localStorage, BEST_KEY);
		game.streak = readNumber(window.localStorage, STREAK_KEY);
		game.queue = nextQueue(game.rounds, game.random);
		nextRound();

		$("next").addEventListener("click", () => {
			game.roundNumber += 1;
			nextRound();
		});
		$("restart").addEventListener("click", restart);
	}

	// Exported for the test harness; the browser just runs boot().
	if (typeof module !== "undefined" && module.exports) {
		module.exports = { buildRound, verdictFor, shuffle, nextQueue, game };
	} else {
		window.__spotTheFake = { buildRound, verdictFor, shuffle, nextQueue, game, boot };
		boot().catch((error) => {
			const board = $("board");
			if (board) board.innerHTML = `<p class="hint">Could not start: ${error.message}</p>`;
		});
	}
})();
